// 🚀 Generated by the 'Export JavaScript.lua' Aseprite script!
// https://github.com/danprince/aseprite-config

/**
 * @typedef {object} Point
 * @prop {number} x
 * @prop {number} y
 *
 * @typedef {object} Rectangle
 * @prop {number} x
 * @prop {number} y
 * @prop {number} width
 * @prop {number} height
 *
 * @typedef {object} Sprite An Aseprite slice.
 * @prop {string} url The url of the sprite's texture.
 * @prop {number} x The x coordinate of the top left of the sprite.
 * @prop {number} y The y coordinate of the top left of the sprite.
 * @prop {number} width The width of the sprite in pixels.
 * @prop {number} height The height of the sprite in pixels.
 * @prop {Point} [pivot] The coordinates of the sprite's pivot point.
 * @prop {Rectangle} [center] The central rectangle of the 9-slice.
 * @prop {string} [data] User-data for the sprite.
 *
 * @typedef {Sprite & { center: Rectangle }} NineSliceSprite
 * @typedef {Sprite & { pivot: Point }} PivotSprite
 */

export const $url = "./sprites.png";
export const anim_card_frame_selected = { height: 24, url: $url, width: 96, x: 288, y: 48, };
export const banner_monster = { height: 24, url: $url, width: 96, x: 96, y: 288, };
export const banner_neutral = { height: 24, url: $url, width: 96, x: 96, y: 264, };
export const banner_victory = { height: 24, url: $url, width: 96, x: 96, y: 312, };
export const button = { center: { height: 2, width: 1, x: 3, y: 3, }, height: 10, url: $url, width: 7, x: 120, y: 24, };
export const button_achievements = { height: 24, url: $url, width: 24, x: 96, y: 72, };
export const button_active = { center: { height: 2, width: 1, x: 3, y: 4, }, height: 10, url: $url, width: 7, x: 127, y: 24, };
export const button_deck = { height: 24, url: $url, width: 24, x: 72, y: 72, };
export const button_disabled = { center: { height: 2, width: 1, x: 3, y: 3, }, height: 10, url: $url, width: 7, x: 134, y: 24, };
export const button_feather = { height: 24, url: $url, width: 24, x: 48, y: 72, };
export const button_gold = { height: 24, url: $url, width: 24, x: 24, y: 72, };
export const button_graveyard = { height: 24, url: $url, width: 24, x: 168, y: 72, };
export const button_leave = { height: 24, url: $url, width: 24, x: 0, y: 72, };
export const button_new_game = { height: 24, url: $url, width: 24, x: 120, y: 72, };
export const button_settings = { height: 24, url: $url, width: 24, x: 144, y: 72, };
export const card_abbess = { height: 24, url: $url, width: 24, x: 96, y: 120, };
export const card_back_human = { height: 24, url: $url, width: 24, x: 168, y: 48, };
export const card_back_monster = { height: 24, url: $url, width: 24, x: 192, y: 48, };
export const card_back_neutral = { height: 24, url: $url, width: 24, x: 216, y: 48, };
export const card_bard = { height: 24, url: $url, width: 24, x: 144, y: 120, };
export const card_bedouin = { height: 24, url: $url, width: 24, x: 360, y: 96, };
export const card_bones = { height: 24, url: $url, width: 24, x: 72, y: 168, };
export const card_brawler = { height: 24, url: $url, width: 24, x: 120, y: 96, };
export const card_butcher = { height: 24, url: $url, width: 24, x: 264, y: 96, };
export const card_caller = { height: 24, url: $url, width: 24, x: 336, y: 120, };
export const card_captain = { height: 24, url: $url, width: 24, x: 48, y: 96, };
export const card_cardinal = { height: 24, url: $url, width: 24, x: 264, y: 120, };
export const card_champion = { height: 24, url: $url, width: 24, x: 72, y: 120, };
export const card_chest = { height: 24, url: $url, width: 24, x: 0, y: 168, };
export const card_chest_open = { height: 24, url: $url, width: 24, x: 24, y: 168, };
export const card_commander = { height: 24, url: $url, width: 24, x: 48, y: 120, };
export const card_cultist = { height: 24, url: $url, width: 24, x: 216, y: 120, };
export const card_demon = { height: 24, url: $url, width: 24, x: 216, y: 144, };
export const card_egg = { height: 24, url: $url, width: 24, x: 120, y: 168, };
export const card_fire = { height: 24, url: $url, width: 24, x: 144, y: 168, };
export const card_frame_rare = { height: 24, url: $url, width: 24, x: 264, y: 48, };
export const card_frame_uncommon = { height: 24, url: $url, width: 24, x: 240, y: 48, };
export const card_friar = { height: 24, url: $url, width: 24, x: 168, y: 96, };
export const card_ghost = { height: 24, url: $url, width: 24, x: 360, y: 120, };
export const card_ghostly_gryphon = { height: 24, url: $url, width: 24, x: 144, y: 144, };
export const card_gladiator = { height: 24, url: $url, width: 24, x: 336, y: 96, };
export const card_gravedigger = { height: 24, url: $url, width: 24, x: 240, y: 120, };
export const card_gryphon = { height: 24, url: $url, width: 24, x: 0, y: 144, };
export const card_gryphon_bones = { height: 24, url: $url, width: 24, x: 96, y: 168, };
export const card_herbalist = { height: 24, url: $url, width: 24, x: 96, y: 96, };
export const card_hermit = { height: 24, url: $url, width: 24, x: 408, y: 96, };
export const card_hero = { height: 24, url: $url, width: 24, x: 0, y: 120, };
export const card_horned_gryphon = { height: 24, url: $url, width: 24, x: 96, y: 144, };
export const card_hunter = { height: 24, url: $url, width: 24, x: 144, y: 96, };
export const card_knight = { height: 24, url: $url, width: 24, x: 312, y: 96, };
export const card_lich = { height: 24, url: $url, width: 24, x: 288, y: 120, };
export const card_lord = { height: 24, url: $url, width: 24, x: 120, y: 120, };
export const card_marksman = { height: 24, url: $url, width: 24, x: 240, y: 96, };
export const card_matriarch_gryphon = { height: 24, url: $url, width: 24, x: 264, y: 144, };
export const card_mean_gryphon = { height: 24, url: $url, width: 24, x: 48, y: 144, };
export const card_messenger = { height: 24, url: $url, width: 24, x: 72, y: 96, };
export const card_monk = { height: 24, url: $url, width: 24, x: 192, y: 96, };
export const card_peasant = { height: 24, url: $url, width: 24, x: 24, y: 96, };
export const card_prophet = { height: 24, url: $url, width: 24, x: 216, y: 96, };
export const card_proud_gryphon = { height: 24, url: $url, width: 24, x: 72, y: 144, };
export const card_pyromancer = { height: 24, url: $url, width: 24, x: 384, y: 96, };
export const card_rememberer = { height: 24, url: $url, width: 24, x: 384, y: 120, };
export const card_restless_gryphon = { height: 24, url: $url, width: 24, x: 120, y: 144, };
export const card_rocks = { height: 24, url: $url, width: 24, x: 48, y: 168, };
export const card_skeletal_gryphon = { height: 24, url: $url, width: 24, x: 168, y: 144, };
export const card_spearman = { height: 24, url: $url, width: 24, x: 288, y: 96, };
export const card_surgeon = { height: 24, url: $url, width: 24, x: 168, y: 120, };
export const card_thorny_gryphon = { height: 24, url: $url, width: 24, x: 240, y: 144, };
export const card_thrall = { height: 24, url: $url, width: 24, x: 312, y: 120, };
export const card_townsfolk = { height: 24, url: $url, width: 24, x: 0, y: 96, };
export const card_wizard = { height: 24, url: $url, width: 24, x: 24, y: 120, };
export const card_woundstress = { height: 24, url: $url, width: 24, x: 408, y: 120, };
export const card_wytch = { height: 24, url: $url, width: 24, x: 192, y: 120, };
export const card_young_gryphon = { height: 24, url: $url, width: 24, x: 24, y: 144, };
export const counter_frame_human = { height: 11, url: $url, width: 9, x: 64, y: 16, };
export const counter_frame_monster = { height: 11, url: $url, width: 9, x: 73, y: 16, };
export const counter_frame_neutral = { height: 11, url: $url, width: 9, x: 82, y: 16, };
export const font = { height: 48, url: $url, width: 64, x: 0, y: 0, };
export const gryphon_caw = { height: 24, url: $url, width: 24, x: 192, y: 144, };
export const icon_arrow = { height: 8, url: $url, width: 8, x: 104, y: 0, };
export const icon_damage = { height: 8, url: $url, width: 8, x: 80, y: 8, };
export const icon_defeat = { height: 8, url: $url, width: 8, x: 112, y: 0, };
export const icon_discard = { height: 8, url: $url, width: 8, x: 104, y: 8, };
export const icon_draw = { height: 8, url: $url, width: 8, x: 96, y: 8, };
export const icon_feather = { height: 8, url: $url, width: 8, x: 88, y: 0, };
export const icon_flag = { height: 8, url: $url, width: 8, x: 96, y: 0, };
export const icon_flying = { height: 8, url: $url, width: 8, x: 72, y: 8, };
export const icon_gold = { height: 8, url: $url, width: 8, x: 80, y: 0, };
export const icon_heal = { height: 8, url: $url, width: 8, x: 64, y: 8, };
export const icon_left = { height: 8, url: $url, width: 8, x: 64, y: 0, };
export const icon_play = { height: 8, url: $url, width: 8, x: 88, y: 8, };
export const icon_question = { height: 8, url: $url, width: 8, x: 112, y: 16, };
export const icon_right = { height: 8, url: $url, width: 8, x: 72, y: 0, };
export const icon_shuffle = { height: 8, url: $url, width: 8, x: 112, y: 8, };
export const indicator_arrows_damage = { height: 24, url: $url, width: 24, x: 288, y: 24, };
export const indicator_arrows_heal = { height: 24, url: $url, width: 24, x: 312, y: 24, };
export const indicator_arrows_move = { height: 24, url: $url, width: 24, x: 360, y: 24, };
export const indicator_arrows_special = { height: 24, url: $url, width: 24, x: 336, y: 24, };
export const intent_path_damage = { height: 3, url: $url, width: 3, x: 91, y: 16, };
export const intent_path_heal = { height: 3, url: $url, width: 3, x: 94, y: 16, };
export const intent_path_special = { height: 3, url: $url, width: 3, x: 97, y: 16, };
export const logo = { height: 48, url: $url, width: 120, x: 192, y: 264, };
export const morale_flag = { height: 24, url: $url, width: 24, x: 216, y: 72, };
export const morale_flag_pole = { height: 24, url: $url, width: 24, x: 192, y: 72, };
export const panel = { center: { height: 6, width: 6, x: 3, y: 3, }, height: 12, url: $url, width: 12, x: 120, y: 0, };
export const panel_hand = { center: { height: 6, width: 6, x: 3, y: 3, }, height: 12, url: $url, width: 12, x: 132, y: 0, };
export const panel_shop = { center: { height: 2, width: 2, x: 6, y: 6, }, height: 14, url: $url, width: 14, x: 168, y: 0, };
export const panel_shop_select = { center: { height: 2, width: 2, x: 6, y: 6, }, height: 14, url: $url, width: 14, x: 168, y: 14, };
export const panel_table = { center: { height: 6, width: 6, x: 3, y: 3, }, height: 12, url: $url, width: 12, x: 132, y: 12, };
export const panel_white = { center: { height: 6, width: 6, x: 3, y: 3, }, height: 12, url: $url, width: 12, x: 120, y: 12, };
export const panel_worn = { center: { height: 2, width: 2, x: 11, y: 11, }, height: 24, url: $url, width: 24, x: 144, y: 0, };
export const shop_title = { height: 13, pivot: { x: 45, y: 5, }, url: $url, width: 91, x: 192, y: 312, };
export const stack_discard = { height: 24, url: $url, width: 24, x: 120, y: 48, };
export const stack_draw = { height: 24, url: $url, width: 24, x: 96, y: 48, };
export const stack_empty = { height: 24, url: $url, width: 24, x: 72, y: 48, };
export const stack_grave = { height: 24, url: $url, width: 24, x: 144, y: 48, };
export const tile_empty = { height: 24, url: $url, width: 24, x: 48, y: 48, };
export const ui_tile_active = { height: 24, url: $url, width: 24, x: 0, y: 48, };
export const ui_tile_empty = { height: 24, url: $url, width: 24, x: 24, y: 48, };
export const vfx_bump = { height: 24, url: $url, width: 96, x: 0, y: 384, };
export const vfx_burn = { height: 24, url: $url, width: 96, x: 0, y: 360, };
export const vfx_claw = { height: 24, url: $url, width: 96, x: 0, y: 288, };
export const vfx_heal = { height: 24, url: $url, width: 96, x: 0, y: 312, };
export const vfx_magic = { height: 24, url: $url, width: 96, x: 0, y: 336, };
export const vfx_slash = { height: 24, url: $url, width: 96, x: 0, y: 264, };
