// 🚀 Generated by the 'Export JavaScript.lua' Aseprite script!
// https://github.com/danprince/aseprite-config

/**
 * @typedef {object} Point
 * @prop {number} x
 * @prop {number} y
 *
 * @typedef {object} Rectangle
 * @prop {number} x
 * @prop {number} y
 * @prop {number} width
 * @prop {number} height
 *
 * @typedef {object} Sprite An Aseprite slice.
 * @prop {string} url The url of the sprite's texture.
 * @prop {number} x The x coordinate of the top left of the sprite.
 * @prop {number} y The y coordinate of the top left of the sprite.
 * @prop {number} width The width of the sprite in pixels.
 * @prop {number} height The height of the sprite in pixels.
 * @prop {Point} [pivot] The coordinates of the sprite's pivot point.
 * @prop {Rectangle} [center] The central rectangle of the 9-slice.
 * @prop {string} [data] User-data for the sprite.
 *
 * @typedef {Sprite & { center: Rectangle }} NineSliceSprite
 * @typedef {Sprite & { pivot: Point }} PivotSprite
 */

export const $url = "./sprites.png";
export const banner_monster = { y: 288, url: $url, height: 24, width: 96, x: 96, };
export const banner_neutral = { y: 264, url: $url, height: 24, width: 96, x: 96, };
export const banner_victory = { y: 312, url: $url, height: 24, width: 96, x: 96, };
export const button = { y: 24, url: $url, height: 10, width: 7, center: { y: 3, width: 1, height: 2, x: 3, }, x: 120, };
export const button_achievements = { y: 72, url: $url, height: 24, width: 24, x: 96, };
export const button_active = { y: 24, url: $url, height: 10, width: 7, center: { y: 4, width: 1, height: 2, x: 3, }, x: 127, };
export const button_altar = { y: 72, url: $url, height: 24, width: 24, x: 240, };
export const button_deck = { y: 72, url: $url, height: 24, width: 24, x: 72, };
export const button_disabled = { y: 24, url: $url, height: 10, width: 7, center: { y: 3, width: 1, height: 2, x: 3, }, x: 134, };
export const button_feather = { y: 72, url: $url, height: 24, width: 24, x: 48, };
export const button_gold = { y: 72, url: $url, height: 24, width: 24, x: 24, };
export const button_graveyard = { y: 72, url: $url, height: 24, width: 24, x: 168, };
export const button_healer = { y: 72, url: $url, height: 24, width: 24, x: 216, };
export const button_hunt = { y: 72, url: $url, height: 24, width: 24, x: 264, };
export const button_leave = { y: 72, url: $url, height: 24, width: 24, x: 0, };
export const button_new_game = { y: 72, url: $url, height: 24, width: 24, x: 120, };
export const button_settings = { y: 72, url: $url, height: 24, width: 24, x: 144, };
export const button_shop = { y: 72, url: $url, height: 24, width: 24, x: 192, };
export const card_apostle = { y: 120, url: $url, height: 24, width: 24, x: 24, };
export const card_bones = { y: 168, url: $url, height: 24, width: 24, x: 72, };
export const card_chest = { y: 168, url: $url, height: 24, width: 24, x: 0, };
export const card_chest_open = { y: 168, url: $url, height: 24, width: 24, x: 24, };
export const card_cleric = { y: 96, url: $url, height: 24, width: 24, x: 24, };
export const card_commander = { y: 96, url: $url, height: 24, width: 24, x: 192, };
export const card_dread = { y: 216, url: $url, height: 24, width: 24, x: 48, };
export const card_egg = { y: 168, url: $url, height: 24, width: 24, x: 120, };
export const card_executioner = { y: 96, url: $url, height: 24, width: 24, x: 264, };
export const card_fear = { y: 216, url: $url, height: 24, width: 24, x: 0, };
export const card_fire = { y: 168, url: $url, height: 24, width: 24, x: 144, };
export const card_ghostly_gryphon = { y: 144, url: $url, height: 24, width: 24, x: 144, };
export const card_gladiator = { y: 96, url: $url, height: 24, width: 24, x: 168, };
export const card_grave_robber = { y: 96, url: $url, height: 24, width: 24, x: 240, };
export const card_gryphon = { y: 144, url: $url, height: 24, width: 24, x: 0, };
export const card_gryphon_bones = { y: 168, url: $url, height: 24, width: 24, x: 96, };
export const card_guardian = { y: 120, url: $url, height: 24, width: 24, x: 144, };
export const card_herbalist = { y: 120, url: $url, height: 24, width: 24, x: 0, };
export const card_hero = { y: 96, url: $url, height: 24, width: 24, x: 144, };
export const card_hunter = { y: 96, url: $url, height: 24, width: 24, x: 0, };
export const card_knight = { y: 96, url: $url, height: 24, width: 24, x: 48, };
export const card_lich = { y: 96, url: $url, height: 24, width: 24, x: 72, };
export const card_mean_gryphon = { y: 144, url: $url, height: 24, width: 24, x: 48, };
export const card_miner = { y: 96, url: $url, height: 24, width: 24, x: 216, };
export const card_peasant = { y: 120, url: $url, height: 24, width: 24, x: 120, };
export const card_plague_doctor = { y: 120, url: $url, height: 24, width: 24, x: 48, };
export const card_proud_gryphon = { y: 144, url: $url, height: 24, width: 24, x: 72, };
export const card_pyromancer = { y: 120, url: $url, height: 24, width: 24, x: 96, };
export const card_restless_gryphon = { y: 144, url: $url, height: 24, width: 24, x: 120, };
export const card_rocks = { y: 168, url: $url, height: 24, width: 24, x: 48, };
export const card_scout = { y: 120, url: $url, height: 24, width: 24, x: 72, };
export const card_skeletal_gryphon = { y: 144, url: $url, height: 24, width: 24, x: 168, };
export const card_stone_gryphon = { y: 144, url: $url, height: 24, width: 24, x: 96, };
export const card_terror = { y: 216, url: $url, height: 24, width: 24, x: 24, };
export const card_thrall = { y: 96, url: $url, height: 24, width: 24, x: 96, };
export const card_wizard = { y: 96, url: $url, height: 24, width: 24, x: 120, };
export const card_young_gryphon = { y: 144, url: $url, height: 24, width: 24, x: 24, };
export const counter_frame_human = { y: 16, url: $url, height: 11, width: 9, x: 64, };
export const counter_frame_monster = { y: 16, url: $url, height: 11, width: 9, x: 73, };
export const counter_frame_neutral = { y: 16, url: $url, height: 11, width: 9, x: 82, };
export const font = { y: 0, url: $url, height: 48, width: 64, x: 0, };
export const icon_arrow = { y: 0, url: $url, height: 8, width: 8, x: 104, };
export const icon_damage = { y: 8, url: $url, height: 8, width: 8, x: 80, };
export const icon_defeat = { y: 0, url: $url, height: 8, width: 8, x: 112, };
export const icon_discard = { y: 8, url: $url, height: 8, width: 8, x: 104, };
export const icon_draw = { y: 8, url: $url, height: 8, width: 8, x: 96, };
export const icon_feather = { y: 0, url: $url, height: 8, width: 8, x: 88, };
export const icon_flag = { y: 0, url: $url, height: 8, width: 8, x: 96, };
export const icon_flying = { y: 8, url: $url, height: 8, width: 8, x: 72, };
export const icon_gold = { y: 0, url: $url, height: 8, width: 8, x: 80, };
export const icon_heal = { y: 8, url: $url, height: 8, width: 8, x: 64, };
export const icon_left = { y: 0, url: $url, height: 8, width: 8, x: 64, };
export const icon_play = { y: 8, url: $url, height: 8, width: 8, x: 88, };
export const icon_right = { y: 0, url: $url, height: 8, width: 8, x: 72, };
export const icon_shuffle = { y: 8, url: $url, height: 8, width: 8, x: 112, };
export const logo = { y: 264, url: $url, height: 48, width: 120, x: 192, };
export const panel = { y: 0, url: $url, height: 12, width: 12, center: { y: 3, width: 6, height: 6, x: 3, }, x: 120, };
export const panel_hand = { y: 0, url: $url, height: 12, width: 12, center: { y: 3, width: 6, height: 6, x: 3, }, x: 132, };
export const panel_shop = { y: 0, url: $url, height: 14, width: 14, center: { y: 6, width: 2, height: 2, x: 6, }, x: 168, };
export const panel_shop_select = { y: 14, url: $url, height: 14, width: 14, center: { y: 6, width: 2, height: 2, x: 6, }, x: 168, };
export const panel_table = { y: 12, url: $url, height: 12, width: 12, center: { y: 3, width: 6, height: 6, x: 3, }, x: 132, };
export const panel_white = { y: 12, url: $url, height: 12, width: 12, center: { y: 3, width: 6, height: 6, x: 3, }, x: 120, };
export const panel_worn = { y: 0, url: $url, height: 24, width: 24, center: { y: 11, width: 2, height: 2, x: 11, }, x: 144, };
export const shop_title = { y: 312, url: $url, height: 13, width: 91, pivot: { y: 5, x: 45, }, x: 192, };
export const stack_discard = { y: 48, url: $url, height: 24, width: 24, x: 120, };
export const stack_draw = { y: 48, url: $url, height: 24, width: 24, x: 96, };
export const stack_empty = { y: 48, url: $url, height: 24, width: 24, x: 72, };
export const stack_grave = { y: 48, url: $url, height: 24, width: 24, x: 144, };
export const tile_empty = { y: 48, url: $url, height: 24, width: 24, x: 48, };
export const ui_tile_active = { y: 48, url: $url, height: 24, width: 24, x: 0, };
export const ui_tile_empty = { y: 48, url: $url, height: 24, width: 24, x: 24, };
export const vfx_bump = { y: 384, url: $url, height: 24, width: 96, x: 0, };
export const vfx_burn = { y: 360, url: $url, height: 24, width: 96, x: 0, };
export const vfx_claw = { y: 288, url: $url, height: 24, width: 96, x: 0, };
export const vfx_heal = { y: 312, url: $url, height: 24, width: 96, x: 0, };
export const vfx_magic = { y: 336, url: $url, height: 24, width: 96, x: 0, };
export const vfx_slash = { y: 264, url: $url, height: 24, width: 96, x: 0, };
