// 🚀 Generated by the 'Export JavaScript.lua' Aseprite script!
// https://github.com/danprince/aseprite-scripts

/**
 * @typedef {object} Point
 * @prop {number} x
 * @prop {number} y
 *
 * @typedef {object} Rectangle
 * @prop {number} x
 * @prop {number} y
 * @prop {number} width
 * @prop {number} height
 *
 * @typedef {object} Sprite An Aseprite slice.
 * @prop {string} url The url of the sprite's texture.
 * @prop {number} x The x coordinate of the top left of the sprite.
 * @prop {number} y The y coordinate of the top left of the sprite.
 * @prop {number} width The width of the sprite in pixels.
 * @prop {number} height The height of the sprite in pixels.
 * @prop {Point} [pivot] The coordinates of the sprite's pivot point.
 * @prop {Rectangle} [center] The central rectangle of the 9-slice.
 * @prop {string} [data] User-data for the sprite.
 *
 * @typedef {Sprite & { center: Rectangle }} NineSliceSprite
 * @typedef {Sprite & { pivot: Point }} PivotSprite
 */

export const $url = "./sprites.png";
export const card_back = { y: 96, url: $url, height: 24, width: 24, x: 96, };
export const button_end_turn_2_active = { y: 224, url: $url, height: 16, width: 37, x: 0, };
export const button_end_turn_2_hover = { y: 208, url: $url, height: 16, width: 37, x: 0, };
export const button_end_turn_2 = { y: 192, url: $url, height: 16, width: 37, x: 0, };
export const stack_grave = { y: 72, url: $url, height: 24, width: 24, x: 96, };
export const stack_discard = { y: 48, url: $url, height: 24, width: 24, x: 96, };
export const stack_empty = { y: 72, url: $url, height: 24, width: 24, x: 72, };
export const panel_table = { y: 72, url: $url, height: 24, width: 24, center: { y: 3, width: 18, height: 18, x: 3, }, x: 48, };
export const stack_draw = { y: 48, url: $url, height: 24, width: 24, x: 72, };
export const icon_flag = { y: 0, url: $url, height: 8, width: 8, x: 96, };
export const icon_feather = { y: 0, url: $url, height: 8, width: 8, x: 88, };
export const icon_gold = { y: 0, url: $url, height: 8, width: 8, x: 80, };
export const icon_right = { y: 0, url: $url, height: 8, width: 8, x: 72, };
export const icon_left = { y: 0, url: $url, height: 8, width: 8, x: 64, };
export const card_dread = { y: 144, url: $url, height: 24, width: 24, x: 168, };
export const card_terror = { y: 144, url: $url, height: 24, width: 24, x: 144, };
export const card_fear = { y: 144, url: $url, height: 24, width: 24, x: 120, };
export const card_bomb = { y: 120, url: $url, height: 24, width: 24, x: 168, };
export const card_key = { y: 120, url: $url, height: 24, width: 24, x: 144, };
export const card_chest = { y: 120, url: $url, height: 24, width: 24, x: 120, };
export const card_skeletal_gryphon = { y: 96, url: $url, height: 24, width: 24, x: 240, };
export const card_king_gryphon = { y: 96, url: $url, height: 24, width: 24, x: 216, };
export const card_furious_gryphon = { y: 96, url: $url, height: 24, width: 24, x: 192, };
export const card_odd_gryphon = { y: 96, url: $url, height: 24, width: 24, x: 168, };
export const card_weird_gryphon = { y: 96, url: $url, height: 24, width: 24, x: 264, };
export const card_gryphon = { y: 96, url: $url, height: 24, width: 24, x: 120, };
export const card_lich = { y: 72, url: $url, height: 24, width: 24, x: 192, };
export const card_knight = { y: 72, url: $url, height: 24, width: 24, x: 168, };
export const card_cleric = { y: 72, url: $url, height: 24, width: 24, x: 144, };
export const card_hunter = { y: 72, url: $url, height: 24, width: 24, x: 120, };
export const button_back = { y: 48, url: $url, height: 24, width: 24, x: 408, };
export const button_end_turn = { y: 48, url: $url, height: 24, width: 24, x: 360, };
export const button_draw = { y: 48, url: $url, height: 24, width: 24, x: 336, };
export const button_discard = { y: 48, url: $url, height: 24, width: 24, x: 312, };
export const button_graveyard = { y: 48, url: $url, height: 24, width: 24, x: 288, };
export const button_settings = { y: 48, url: $url, height: 24, width: 24, x: 264, };
export const button_new_game = { y: 48, url: $url, height: 24, width: 24, x: 240, };
export const button_achievements = { y: 48, url: $url, height: 24, width: 24, x: 216, };
export const button_deck = { y: 48, url: $url, height: 24, width: 24, x: 192, };
export const button_feather = { y: 48, url: $url, height: 24, width: 24, x: 168, };
export const button_gold = { y: 48, url: $url, height: 24, width: 24, x: 144, };
export const button_leave = { y: 48, url: $url, height: 24, width: 24, x: 120, };
export const button_hunt = { y: 24, url: $url, height: 24, width: 24, x: 192, };
export const button_altar = { y: 24, url: $url, height: 24, width: 24, x: 168, };
export const button_healer = { y: 24, url: $url, height: 24, width: 24, x: 144, };
export const button_shop = { y: 24, url: $url, height: 24, width: 24, x: 120, };
export const tile_empty = { y: 0, url: $url, height: 24, width: 24, x: 168, };
export const ui_tile_empty = { y: 0, url: $url, height: 24, width: 24, x: 144, };
export const ui_tile_active = { y: 0, url: $url, height: 24, width: 24, x: 120, };
export const banner_victory = { y: 168, url: $url, height: 24, width: 96, x: 0, };
export const banner_monster = { y: 144, url: $url, height: 24, width: 96, x: 0, };
export const banner_neutral = { y: 120, url: $url, height: 24, width: 96, x: 0, };
export const panel_hand = { y: 48, url: $url, height: 24, width: 24, center: { y: 3, width: 18, height: 18, x: 3, }, x: 48, };
export const panel = { y: 48, url: $url, height: 24, width: 24, center: { y: 3, width: 18, height: 18, x: 3, }, x: 0, };
export const panel_worn = { y: 48, url: $url, height: 24, width: 24, center: { y: 11, width: 2, height: 2, x: 11, }, x: 24, };
export const font = { y: 0, url: $url, height: 48, width: 64, x: 0, };
export const logo = { y: -1, url: $url, height: 49, width: 121, x: 216, };
export const panel_divider = { y: 96, url: $url, height: 3, width: 96, x: 0, };
export const card_active = { y: 0, url: $url, height: 24, width: 24, x: 192, };
export const vfx_slash = { y: 216, url: $url, height: 24, width: 96, x: 120, };
export const vfx_claw = { y: 240, url: $url, height: 24, width: 96, x: 120, };
export const card_young_gryphon = { y: 96, url: $url, height: 24, width: 24, x: 144, };
export const counter_frame_monster = { y: 16, url: $url, height: 11, width: 9, x: 73, };
export const counter_frame_human = { y: 16, url: $url, height: 11, width: 9, x: 64, };
export const counter_frame_neutral = { y: 16, url: $url, height: 11, width: 9, x: 82, };
export const button_end_hunt = { y: 48, url: $url, height: 24, width: 24, x: 384, };
export const icon_vanish = { y: 0, url: $url, height: 8, width: 8, x: 104, };
export const button_frame_gold = { y: 72, url: $url, height: 12, width: 12, center: { y: 3, width: 6, height: 6, x: 3, }, x: 0, };
export const button_frame_burnished_gold = { y: 72, url: $url, height: 12, width: 12, center: { y: 3, width: 6, height: 6, x: 3, }, x: 12, };
export const card_rocks = { y: 120, url: $url, height: 24, width: 24, x: 192, };
export const card_bones = { y: 120, url: $url, height: 24, width: 24, x: 216, };
export const icon_skull = { y: 0, url: $url, height: 8, width: 8, x: 112, };
export const vfx_heal = { y: 264, url: $url, height: 24, width: 96, x: 120, };
export const icon_heal = { y: 8, url: $url, height: 8, width: 8, x: 64, };
export const card_trapper = { y: 72, url: $url, height: 24, width: 24, x: 240, };
export const card_hero = { y: 72, url: $url, height: 24, width: 24, x: 264, };
export const icon_flying = { y: 8, url: $url, height: 8, width: 8, x: 72, };
export const card_restless_gryphon = { y: 96, url: $url, height: 24, width: 24, x: 288, };
export const icon_knockback = { y: 8, url: $url, height: 8, width: 8, x: 80, };
export const card_thrall = { y: 72, url: $url, height: 24, width: 24, x: 216, };
export const card_gladiator = { y: 72, url: $url, height: 24, width: 24, x: 288, };
export const icon_attack = { y: 8, url: $url, height: 8, width: 8, x: 88, };
